# Placeholder until the first signed GitHub Release exists.
# Generated by: scripts/bump-cask.sh <version> <sha256> <zip-url>
# Copy this file to your homebrew-tap repo as Casks/sonar.rb, then:
#   brew audit --cask --strict sonar
#   brew install --cask sonar && brew test sonar && brew uninstall --cask --zap sonar
cask "sonar" do
  version "0.1.0"
  sha256 "REPLACE_WITH_RELEASE_SHA256"

  url "https://github.com/you/sonar/releases/download/v0.1.0/Sonar-0.1.0.zip"
  name "Sonar"
  desc "Spotify in your macOS menu bar, with hybrid auto-pause"
  homepage "https://github.com/you/sonar"

  depends_on macos: ">= :sequoia"
  conflicts_with cask: "spotmenu"

  app "Sonar.app"

  zap trash: [
    "~/Library/Caches/com.you.sonar",
    "~/Library/Containers/com.you.sonar",
    "~/Library/Logs/Sonar",
    "~/Library/Preferences/com.you.sonar.plist",
  ]
end
